// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvb9toUQHAg6b5k8hub6uVzYCK6yFnnU8',
    appId: '1:504885357492:web:02a3f056c2e524572b60e1',
    messagingSenderId: '504885357492',
    projectId: 'news-app-e2987',
    authDomain: 'news-app-e2987.firebaseapp.com',
    storageBucket: 'news-app-e2987.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4uyXE6ywyySwMKMDc9F2BtrAFyyZIdWI',
    appId: '1:504885357492:android:cfb66d6d6a7414892b60e1',
    messagingSenderId: '504885357492',
    projectId: 'news-app-e2987',
    storageBucket: 'news-app-e2987.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR25laSu_zWXu_jTlgUmUvydwKBy5lmvY',
    appId: '1:504885357492:ios:cfe5b91187da83272b60e1',
    messagingSenderId: '504885357492',
    projectId: 'news-app-e2987',
    storageBucket: 'news-app-e2987.firebasestorage.app',
    iosBundleId: 'com.flutterians.newstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvb9toUQHAg6b5k8hub6uVzYCK6yFnnU8',
    appId: '1:504885357492:web:a4c78714564209c62b60e1',
    messagingSenderId: '504885357492',
    projectId: 'news-app-e2987',
    authDomain: 'news-app-e2987.firebaseapp.com',
    storageBucket: 'news-app-e2987.firebasestorage.app',
  );
}
